version: '3'

services:
  server:
    build: .
    restart: always
    container_name: api
    ports:
      - '8080:8080'
    volumes:
      - '.:/home/node/app'
    depends_on:
      - db

  db:
    build: .docker/.
    restart: always
    container_name: db
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
